modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="rotatingitems"
version="1.19.2-1.0.0.0"
displayName="RotatingItems"
logoFile="logo.png"
authors="Krakenrek"
displayTest="IGNORE_ALL_VERSION"
description='''Mod that makes items rotate in GUIs'''
[[dependencies.rigui]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rigui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
